import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F5F5F7', 
  },
  page: {
    flex: 1,
    backgroundColor: '#fff',    
    paddingTop:0
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16, 
    gap: 16,
    flexGrow: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
  },
  heading: {
    fontSize: 32,
    fontWeight: '700',
  },
  headerTools: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerToolButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  headerToolButtonDisabled: {
    opacity: 0.6,
  },
  headerToolButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111827',
  },
  headerToolButtonTextDisabled: {
    color: '#94A3B8',
  },
  card: {
    borderRadius: 20,
    gap: 16,
  },
  fullHeightCard: { 
    alignSelf: 'stretch',
    minHeight: 0,
  },
  cardMeta: {
    fontSize: 14,
    color: '#6B7280',
  },
  editor: {
    fontSize: 15,
    lineHeight: 24,
    minHeight: 50,
    flex: 0,
    borderWidth: 0,
  },
  actionsModalContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    justifyContent: 'flex-end',
    pointerEvents: 'box-none',
  },
  actionsModalContent: {
    justifyContent: 'flex-end',
    pointerEvents: 'box-none',
  },
  actionsModalSheet: {
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  sheetBackground: {
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 12,
  },
  sheetIndicator: {
    width: 40,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#D1D5DB',
  },
  sheetContent: {
    paddingHorizontal: 24,
    paddingVertical: 10,
    gap: 6,
  },
  quickActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  quickActionWrapper: {
    position: 'relative',
  },
  quickAction: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
    paddingHorizontal: 12,
    paddingVertical: 8,
    height: 50,
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    borderWidth: 2,
    borderColor: '#fff',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#fff',
  },
  quickActionSelected: {
    borderWidth: 1,
    borderColor: '#111827',
    backgroundColor: '#F9FAFB',
  },
  quickActionIcon: {
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionLabel: {
    fontSize: 12,
    color: '#374151',
  },
  sheetButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    fontWeight: '600',
    fontSize: 14,
    color: '#111827',
  },
  primaryButton: {
    flex: 1.4,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonDisabled: {
    backgroundColor: '#F3F4F6',
  },
  primaryButtonText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '600',
  },
  ghostButton: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ghostButtonText: {
    fontWeight: '600',
    fontSize: 14,
    color: '#fff',
  },
  xCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  xAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#E5E7EB',
  },
  xContent: {
    flex: 1,
    gap: 12,
  },
  xHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  xHeaderText: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  xUserName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0F1419',
  },
  xUserMeta: {
    fontSize: 14,
    color: '#6B7280',
  },
  xEditor: {
    fontSize: 15,
    lineHeight: 24,
    paddingHorizontal: 0,
    paddingVertical: 0,
    color: '#0F1419',
    width: '100%',
    borderWidth: 0,
  },
  xFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 4,
  },
  xEngagementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: 16,
  },
  xEngagementItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flex: 1,
    gap: 4,
  },
  xEngagementValue: {
    fontSize: 13,
    color: '#6B7280',
  },
  threadsEngagementRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 16,
    alignSelf: 'flex-start',
  },
  threadsEngagementItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 4,
  },
  copyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#F3F4F6',
    alignSelf: 'flex-end',
  },
  copyButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#111827',
  },
  postDivider: {
    height: 1,
    backgroundColor: '#ccc',
    width: '100%',
    alignSelf: 'stretch',
    marginTop: 0,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    pointerEvents: 'box-none',
  },
  modalOverlayWeb: {
    alignItems: 'center',
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.25)',
  },
  fixesModalHandle: {
    width: 40,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#D1D5DB',
    alignSelf: 'center',
  },
  cancelButton: {
    flex: 1,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#111827',
  },
  applyButton: {
    flex: 1,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  historyModal: {
    height: '100%',
    backgroundColor: '#fff',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 12,
    paddingHorizontal: 20,
    paddingBottom: 24,
    gap: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 18,
  },
  historyModalWeb: {
    maxWidth: 800,
    width: '100%',
  },
  historyHeader: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  historyTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#111827',
  },
  historyCloseButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
  },
  versionsList: {
    flex: 1,
  },
  versionsListContent: {
    gap: 16,
    paddingBottom: 16,
    flexGrow: 1,
  },
  versionCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    position: 'relative',
  },
  versionLabel: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  versionLabelText: {
    fontSize: 12,
    fontWeight: '500',
    color: '#6B7280',
  },
  versionContent: {
    fontSize: 15,
    lineHeight: 24,
    color: '#111827',
    paddingTop: 8,
    paddingBottom: 8,
  },
  versionButtonsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    justifyContent: 'flex-end',
  },
  versionCopyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#F3F4F6',
  },
  versionCopyButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#111827',
  },
  versionDeleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#FEF2F2',
  },
  versionDeleteButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#EF4444',
  },
  versionDivider: {
    height: 1,
    backgroundColor: 'transparent',
  },
  goalModal: {
    height: '70%',
    backgroundColor: '#fff',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 12,
    paddingHorizontal: 24,
    paddingBottom: 24,
    gap: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 18,
    flexDirection: 'column',
  },
  goalModalWeb: {
    maxWidth: 800,
    width: '100%',
  },
  goalHeader: {
    marginTop: 4,
  },
  goalTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#111827',
  },
  goalButtonsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    flex: 1,
  },
  goalButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  goalButtonSelected: {
    backgroundColor: '#111827',
    borderColor: '#111827',
  },
  goalButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#6B7280',
  },
  goalButtonTextSelected: {
    color: '#fff',
  },
  goalButtons: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 24,
    paddingBottom: 24,
    paddingTop: 12,
    marginTop: 'auto',
  },
  referencesModal: {
    height: '80%',
    backgroundColor: '#fff',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 12,
    paddingHorizontal: 24,
    paddingBottom: 24,
    gap: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 18,
  },
  referencesModalWeb: {
    maxWidth: 800,
    width: '100%',
  },
  referencesHeader: {
    marginTop: 4,
  },
  referencesTitle: {
    fontSize: 32,
    fontWeight: '700',
    color: '#111827',
  },
  addScreenshotButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#fff',
    alignSelf: 'flex-start',
  },
  addScreenshotText: {
    fontSize: 16,
    color: '#6B7280',
  },
  referenceInputContainer: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-end',
  },
  referenceInput: {
    flex: 1,
    minHeight: 100,
    maxHeight: 200,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    borderWidth: 2,
    borderColor: '#3B82F6',
    fontSize: 16,
    color: '#111827',
    textAlignVertical: 'top',
  },
  addReferenceButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#111827',
    alignSelf: 'flex-end',
  },
  addReferenceButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  referencesButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 'auto',
  },
});

